# Generated by Django 4.2.10 on 2024-03-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='difficulty',
            options={'verbose_name_plural': 'Difficulties'},
        ),
    ]
